/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SopNewRouteImport } from './routes/sop.new'
import { Route as SopIdRouteImport } from './routes/sop.$id'
import { Route as SopIdProcedureRouteImport } from './routes/sop.$id.procedure'
import { Route as SopIdOverviewRouteImport } from './routes/sop.$id.overview'
import { Route as SopIdMatricesRouteImport } from './routes/sop.$id.matrices'
import { Route as SopIdHistoryRouteImport } from './routes/sop.$id.history'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SopNewRoute = SopNewRouteImport.update({
  id: '/sop/new',
  path: '/sop/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SopIdRoute = SopIdRouteImport.update({
  id: '/sop/$id',
  path: '/sop/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SopIdProcedureRoute = SopIdProcedureRouteImport.update({
  id: '/procedure',
  path: '/procedure',
  getParentRoute: () => SopIdRoute,
} as any)
const SopIdOverviewRoute = SopIdOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => SopIdRoute,
} as any)
const SopIdMatricesRoute = SopIdMatricesRouteImport.update({
  id: '/matrices',
  path: '/matrices',
  getParentRoute: () => SopIdRoute,
} as any)
const SopIdHistoryRoute = SopIdHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => SopIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sop/$id': typeof SopIdRouteWithChildren
  '/sop/new': typeof SopNewRoute
  '/sop/$id/history': typeof SopIdHistoryRoute
  '/sop/$id/matrices': typeof SopIdMatricesRoute
  '/sop/$id/overview': typeof SopIdOverviewRoute
  '/sop/$id/procedure': typeof SopIdProcedureRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sop/$id': typeof SopIdRouteWithChildren
  '/sop/new': typeof SopNewRoute
  '/sop/$id/history': typeof SopIdHistoryRoute
  '/sop/$id/matrices': typeof SopIdMatricesRoute
  '/sop/$id/overview': typeof SopIdOverviewRoute
  '/sop/$id/procedure': typeof SopIdProcedureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sop/$id': typeof SopIdRouteWithChildren
  '/sop/new': typeof SopNewRoute
  '/sop/$id/history': typeof SopIdHistoryRoute
  '/sop/$id/matrices': typeof SopIdMatricesRoute
  '/sop/$id/overview': typeof SopIdOverviewRoute
  '/sop/$id/procedure': typeof SopIdProcedureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sop/$id'
    | '/sop/new'
    | '/sop/$id/history'
    | '/sop/$id/matrices'
    | '/sop/$id/overview'
    | '/sop/$id/procedure'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/sop/$id'
    | '/sop/new'
    | '/sop/$id/history'
    | '/sop/$id/matrices'
    | '/sop/$id/overview'
    | '/sop/$id/procedure'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sop/$id'
    | '/sop/new'
    | '/sop/$id/history'
    | '/sop/$id/matrices'
    | '/sop/$id/overview'
    | '/sop/$id/procedure'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SopIdRoute: typeof SopIdRouteWithChildren
  SopNewRoute: typeof SopNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sop/new': {
      id: '/sop/new'
      path: '/sop/new'
      fullPath: '/sop/new'
      preLoaderRoute: typeof SopNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sop/$id': {
      id: '/sop/$id'
      path: '/sop/$id'
      fullPath: '/sop/$id'
      preLoaderRoute: typeof SopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sop/$id/procedure': {
      id: '/sop/$id/procedure'
      path: '/procedure'
      fullPath: '/sop/$id/procedure'
      preLoaderRoute: typeof SopIdProcedureRouteImport
      parentRoute: typeof SopIdRoute
    }
    '/sop/$id/overview': {
      id: '/sop/$id/overview'
      path: '/overview'
      fullPath: '/sop/$id/overview'
      preLoaderRoute: typeof SopIdOverviewRouteImport
      parentRoute: typeof SopIdRoute
    }
    '/sop/$id/matrices': {
      id: '/sop/$id/matrices'
      path: '/matrices'
      fullPath: '/sop/$id/matrices'
      preLoaderRoute: typeof SopIdMatricesRouteImport
      parentRoute: typeof SopIdRoute
    }
    '/sop/$id/history': {
      id: '/sop/$id/history'
      path: '/history'
      fullPath: '/sop/$id/history'
      preLoaderRoute: typeof SopIdHistoryRouteImport
      parentRoute: typeof SopIdRoute
    }
  }
}

interface SopIdRouteChildren {
  SopIdHistoryRoute: typeof SopIdHistoryRoute
  SopIdMatricesRoute: typeof SopIdMatricesRoute
  SopIdOverviewRoute: typeof SopIdOverviewRoute
  SopIdProcedureRoute: typeof SopIdProcedureRoute
}

const SopIdRouteChildren: SopIdRouteChildren = {
  SopIdHistoryRoute: SopIdHistoryRoute,
  SopIdMatricesRoute: SopIdMatricesRoute,
  SopIdOverviewRoute: SopIdOverviewRoute,
  SopIdProcedureRoute: SopIdProcedureRoute,
}

const SopIdRouteWithChildren = SopIdRoute._addFileChildren(SopIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SopIdRoute: SopIdRouteWithChildren,
  SopNewRoute: SopNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
